eureka:
  client:
    service-url:
      defaultZone: http://39.106.71.119:8761/eureka/

spring:
  application:
    name: nami

server:
  port: 9000

#一定要做config了
zuul:
  routes:
    #test: /myTest/**   #另一种写法，routes下，直接服务名： 路由到地址
    myTest:
      path: /myTest/**
      serviceId: test
      sensitiveHeaders: #敏感头，设置为空，否则会导致cookie不能传值，原敏感头集合为("Cookie", "Set-Cookie", "Authorization")
  ignored-patterns: #进制访问（正则格式）
    - /test/test/send
    - /myTest/test/send
    #- /**/test/send #可加通配符，等同于以上
  #sensitive-headers: #全局敏感头

#actuator  启用所有的监控端点 “*”号代表启用所有的监控端点，可以单独启用，例如，health，info，metrics
#  spring boot 升为 2.0 后，为了安全，默认 Actuator 只暴露了2个端点，heath 和 info
# 保证了/actuator/routes可访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
